# Run SQL Queries Here

Simple notebook to help you quickly explore the postgres database.

### Steps:

1. Run the below cell and the helper function will connect to postgres and return the results available tables.
2. Use subsequent notebook cells to explore the database with your own sql queries.
  
  

> NOTE: If prompted to select a kernal in GitHub codespaces, please select `/usr/local/bin/python`

In [1]:
from data_contract_components.data_assets._query_postgres_helper import PostgresDB
import pandas as pd

# setup display to show all columns
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

# setup postgres connection
sql = PostgresDB()
sql.query("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'")

                   table_name
0             alembic_version
1                      object
2              object_history
3  object_physical_properties
4         object_gallery_info
5                 object_tags
6               object_images
7            object_copyright
8         object_api_metadata

In [8]:
sql_query_str = """
SELECT * FROM object;
"""
sql.query(sql_query_str)

,object_id,title,artist_display_name,created_at
0,229770,Hunting and fishing scenes,Robert Jones,2026-10-26 11:16:04.053758
1,229936,Quilt,,2026-10-26 11:16:04.053758
2,503615,Bassoon,Giosue Esposito,2026-10-26 11:16:04.053758
3,506724,Clarinet in D,,2026-10-26 11:16:04.053758
4,591841,An Address to the Workmen in the Pottery on th...,Josiah Wedgwood,2026-10-26 11:16:04.053758
...,...,...,...,...
3020,435702,The Horse Fair,Rosa Bonheur,2026-10-26 11:16:08.783612
3021,436964,Young Lady in 1866,Edouard Manet,2026-10-26 11:16:08.783612
3022,435826,The Love Song,Sir Edward Burne-Jones,2026-10-26 11:16:08.783612
3023,436105,The Death of Socrates,Jacques Louis David,2026-10-26 11:16:08.783612
3024,889319,Ghosts : seventy portraits,Hung Liu,2026-10-26 11:16:08.783612